language: node_js
sudo: false
node_js:
- 8
- 9
- 10
- 12
- 13
cache: npm
branches:
  only:
    - master
jobs:
  include:
    - stage: deploy
      node_js: 12
      script: skip
      if: branch = master
      deploy:
        provider: script
        script: bash ./.travis/deploy.sh
        on: master
