language: node_js
node_js:
- 12
cache: npm
services:
  - docker
  - mysql
env:
  global:
  - LOG_LEVEL=debug
  - PORT=3001
  - ENCRYPTION_KEY=b097b390a68441cc3bb151dd0171f25c3aabc688c50eeb26dc5e13254b333911
  - SESSION_KEY=a73545a5f08d2906e39a4438014200303f9269f3ade9227525ffb141294f1b62
  - DB_HOST=127.0.0.1
  - DB_PORT=3306
  - DB_USER=root
  - DB_PASSWORD=
  - DB_CONNECTION_LIMIT=5
branches:
  only:
    - master
after_success:
  - npm run coveralls
jobs:
  include:
    - stage: test
      script: npm test
    - stage: build
      script: docker build .
    - stage: deploy
      node_js: 12
      if: branch = master
      deploy:
        provider: script
        script: bash ./.travis/deploy.sh
        on: master
